### ISSUE TITLE
std.querysort not working properly with WordPress < 5.3.x (and probably others as well)

### ISSUE THREAD

**Issue by click** [mattiasgeniar/varnish-6.0-configuration-templates#4]
Hi, there is a minor issue with using this snippet:
```
# Normalize the query arguments
set req.url = std.querysort(req.url);
```
The main problem here is that WordPress < 5.3.x doesn't like presorted url parameters (messes up wp-admin dashboard icons etc.)
Reference: https://core.trac.wordpress.org/ticket/45346

There's a patch-set for WordPress coming in the next release (slated for mid september alledgedly), but I guess this might actually affect other applications as well, if they require 'specific' ordering.

**Comment by mattiasgeniar** [comment]
Hi @click! Thanks for the heads-up. Unfortunately, that isn't something I can easily fix in the template, it's rather application specific and I want to keep the templates as generic as possible.

It'll show up in the search results (github/google) if others are experiencing the same issue, so they should be able to remove the querysort themselves. 🤗

**Comment by emansom** [comment]
Adding a comment would be informative :)

**Comment by click** [comment]
@mattiasgeniar I know WordPress isn't the only application affected by this issue, but as you said the config is to be considered a 'generic' template. As @emansom mentioned, a minor comment on the function inside the template might be a good idea (something ala "Using std.querysort MAY lead to issues if the backend application handles sorted input in a weird way" (or something along that route).
